# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8afed3895d3667cc5c18f1c2bf5290b5c28f3216b6693cecd19213c2cb4e27104d38f99e1f8b2c1f350974f6c358929bf70a26877c6e01a227d9efbf11864de3

test:
  secret_key_base: 4b0f83f56ae05eb6d1fb8de284ccd9e4bdef00add40c64db46c05baba6eaab09f24319d99d65f5220e98275fa2750dc8ab6e9117c386181939b54ce9b0a3f4f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
